### ISSUE TITLE
Warning: react-modal: App element is not defined.

### ISSUE THREAD

**Issue by arpitprod** [Horat1us/react-image-lightbox-rotate#2]
Showing this warning after update reactjs 

`Warning: react-modal: App element is not defined. Please use `Modal.setAppElement(el)` or set `appElement={el}`. This is needed so screen reades don't see main content when modal is opened. It is not recommended, but you can opt-out by setting `ariaHideApp={false}`.`

check same in react-modal for how to remove this warning
[https://github.com/reactjs/react-modal/issues/576](url)

How to solve same here ?

I asked this question on react-image-lightbox 
[https://github.com/fritz-c/react-image-lightbox/issues/94](url)

they solved this today but it's not still fixed on myside. Maybe cause I'm using react-image-lightbox-rotate plugin 

Please check on your end

**Comment by Horat1us** [comment]
I'll check it during this week.

**Comment by Horat1us** [comment]
I didn't found this bug in my project that use this library.

**Comment by Neilai** [comment]
i have the same problem
